name: Run Automation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create report directory
      run: mkdir -p reports
    
    - name: Run tests
      env:
        SCREENSHOT_DIR: ${{ github.workspace }}/screenshots
        PYTHONUNBUFFERED: 1
      run: |
        pytest -m smoke --html=reports/report.html --self-contained-html

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with: 
        name: pytest-reports
        path: reports/report.html

    - name: Upload screenshots (on failure)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-screenshots
        path: screenshots/